name: Build and Deploy

on:
    # Runs on pushes targeting the default branch
    push:
        branches:
            - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: 'pages'
    cancel-in-progress: false

jobs:
    build:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Get GitHub Pages URL
              run: |
                  owner_name=${GITHUB_REPOSITORY_OWNER}
                  repository_name=${GITHUB_REPOSITORY#*/}
                  public_url=https://${owner_name}.github.io/${repository_name}
                  echo "GH_PAGES_URL : $public_url"
                  echo "GH_PAGES_URL=${public_url}" >> $GITHUB_ENV

            - name: Install dependencies
              run: yarn

            - name: Build module
              run: yarn build --env GH_PAGES_URL=${{ env.GH_PAGES_URL }}

            - name: Build tutorial if not skip
              run: |
                  export SKIP=$(grep SKIP_BUILD_TUTORIAL .env | cut -d '=' -f2 | xargs)
                  if [ "$SKIP" = "true" ]; then
                    echo "Skipping build tutorial";
                  else
                    echo "Starting build tutorial";
                    yarn build:tutorial:gh;
                  fi

            - name: Generate index page
              run: node .github/scripts/generateIndex.js $GITHUB_REPOSITORY
              
            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  # Upload the dist TARGET_MODULE folder only
                  path: './dist'

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
